name: Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show nix version
        run: nix --version

      - name: Check flake
        run: nix flake check

      - name: Build
        working-directory: examples/kboom
        run: nix build .#kboom

      - name: Test
        working-directory: examples/kboom
        run: nix run .#test
